### ISSUE TITLE
spherical shell? 

### ISSUE THREAD

**Issue by jorafb** [evanhanders/plotpal#8]
Hi Evan, 

This is not an issue but a question/request. Is it possible to plot something like this with plotpal (for data on the spherical shell) ?

![S0022112020000671_figAb](https://github.com/evanhanders/plotpal/assets/43425560/374c317e-ba33-4ea1-9386-5ed1418dc61d)

I saw in one of the examples a combination between a sphere (core) and a shell (envelope), but a shell without a sphere has no data between r=0 and r_inner.

**Comment by evanhanders** [comment]
As currently implemented -- nope! If you've made a way to do this and want to commit it back into the main repo we should get a PR together!

**Comment by jorafb** [comment]
Thanks Evan, I will close this because we have implemented this option now. I pushed the final changes including a example.
